# Declare and configure the kinematic solver that moveit has to use for our robot

arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  position_only_ik: True  # this parameter is useful since our robot has only three dof, and so we are asking the inverse kinematic solver to define only the position in the space of the robot.