controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # 'joint_state_broadcaster' is responsible for publishing 
    # the current state of each of those joints of the robot
    # into a topic, making them usable by other nodes that 
    # need to know the position of the robot's arm
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    # Define the list of the joints that are actuated 
    # by this controller
    joints:
      - joint_1
      - joint_2
      - joint_3

    # We want to send position commands to the arm
    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


gripper_controller:
  ros__parameters:
    joints:
      # Only joint_4 belongs to gripper controller
      - joint_4

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true